services:
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'x4n7ry4x7r734nr743hr4743h'
      POSTGRES_DB: 'produto'
    volumes:
      - ./db/project.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 'rafaelsales202205@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'x5y3nt875htr7245ht745ht745h8t745yt745h'
    depends_on:
      - database

  api:
    build: .
    restart: always
    ports:
      - ${PORT}:3000
    environment:
      PORT: ${PORT}
      DB_HOST: 'database'
      DB_USER: 'postgres'
      DB_PASS: 'x4n7ry4x7r734nr743hr4743h'
      DB_NAME: ${DB_NAME}
      JWT_PASS: 'senhaFluxo'
      FROM_MAIL: 'rafaelsales202205@gmail.com'
      MAIL_HOST: 'http://smtp.gmail.com'
      MAIL_PORT: 465
      MAIL_USER: '2017infor45@gmail.com'
      MAIL_PASS: 'aihx fcsu hpzk julv'
      ACCESS_TOKEN: 'TEST-3426154305753593-060916-a6684228339f359e7fa4339e3ed25845-608954520'
    depends_on:
      - database
